# Site version
version: 0.2

# Site settings
title: Eric Garcia
email: eng618@garciaericn.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my professional portfolio!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eng618.github.io" # the base hostname & protocol for your site

# Site variables
color_primary: red
color_accent: deep_purple
google_analytics: UA-64261422-5
twitter_username: garciaericn
github_username:  eng618

# Build settings
markdown: kramdown
permalink: pretty
# show_drafts: true
incremental: true

collections:
  android-apps:
    output: true
    permalink: /apps/android/:path/
  ios-apps:
    output: true
    permalink: /apps/ios/:path/
  notes:
    output: true
    permalink: /notes/:path/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "notes"
    values:
      layouts: "basic-page"
